spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aide_service
    username: aide_service
    password: aide_service
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always  